# Generated by Django 3.1.4 on 2020-12-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ir_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='etest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='EmilyDickinson',
        ),
    ]
