# Generated by Django 3.1.4 on 2020-12-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ir_website', '0002_auto_20201220_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmilyDickinson',
            fields=[
                ('id', models.IntegerField(default=-1, primary_key='True', serialize=False)),
                ('document', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='etest',
        ),
    ]
