# Generated by Django 3.1.4 on 2020-12-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ir_website', '0003_auto_20201220_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalesFromTheNorse',
            fields=[
                ('id', models.IntegerField(default=-1, primary_key='True', serialize=False)),
                ('document', models.TextField()),
            ],
        ),
    ]
