# Generated by Django 3.1.4 on 2020-12-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ir_website', '0004_talesfromthenorse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItalianRecipes',
            fields=[
                ('id', models.IntegerField(default=-1, primary_key='True', serialize=False)),
                ('document', models.TextField()),
            ],
        ),
    ]
